package com.shinysponge.dpscript.project;

import com.shinybunny.utils.fs.Files;
import com.shinysponge.dpscript.DPScriptMain;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class Datapack {


    private File dir;
    private String name;
    private Namespace defaultNamespace;
    private final Namespace minecraftNamespace;
    private List<Namespace> namespaces;
    private String description;

    public Datapack(File dir) {
        this.dir = dir;
        this.name = dir.getName();
        this.namespaces = new ArrayList<>();
        this.namespaces.add(defaultNamespace = new Namespace(dir));
        this.namespaces.add(minecraftNamespace = new Namespace("minecraft"));
        this.description = "A minecraft datapack (Generated by DPScript)";
    }

    public String getName() {
        return name;
    }

    public List<Namespace> getNamespaces() {
        return namespaces;
    }

    public Namespace getDefaultNamespace() {
        return defaultNamespace;
    }

    public Namespace getMinecraftNamespace() {
        return minecraftNamespace;
    }

    public File getDir() {
        return dir;
    }

    public void save(File dest) {
        File root = Files.create(dest,name);
        Files.createIfNotExists(root);
        DPScriptMain.generateMCMeta(root,description);
        File data = Files.create(root,"data");
        for (Namespace ns : namespaces) {
            ns.saveIn(data);
        }
    }
}
